"""Added user2

Revision ID: 64af900bf397
Revises: f02d1205dd90
Create Date: 2021-06-04 12:13:20.915732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64af900bf397'
down_revision = 'f02d1205dd90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.device_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('device', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'password')
    op.drop_table('user_device')
    # ### end Alembic commands ###
